project:
  type: website

website:
  title: "Doc-theme"
  favicon: "images/favicon.svg"
  navbar:
    pinned: true
  sidebar:
    style: "docked"
    collapse-level: 1
    search: true
    pinned: false
    contents:
      - text: "Introduction"
        href: index.qmd
      - section: "Getting Started"
        contents:
          - files/file-1.qmd
          - files/file-2.qmd
  page-footer:
    left: |
      © 2024 Posit Software, PBC formerly RStudio, PBC 
    center: |
      Posit Product 12345 

    right:
      - icon: book
        href: https://docs.posit.co
      - icon: question-circle-fill
        href: https://support.posit.co/hc/en-us
      - icon: lightbulb-fill
        href: https://solutions.posit.co
      - text: "<img src='/images/posit-logo-black-TM.png' id='footer-logo'>"
        url: "https://posit.co"
format:
  html:
    theme: 
      - theme.scss
    link-external-icon: true
    link-external-newwindow: true
    toc: true



